### ISSUE TITLE
portscout adds ports with versions having a 'v' prefix to the list of ports that have a new version available

### ISSUE THREAD

**Issue by yurivict** [freebsd/portscout#11] opened 2020-02-29 18:47 UTC
When a version has 'v' (or other) prefix on GitHub and in the ```DISTVERSIONPREFIX``` line in Makefile, the ports like this are often added to the "ports that have new versions available".

Among the ports that I maintain there are currently several cases like this. Ex. math/rumur with 2020.02.17-1 and v2020.02.17-1, misc/dynomite with 0.6.21-rc2 and v0.6.21-rc2, devel/libsimdpp with 2.1 and cxx98-v2.1.

@koobs

**Comment by koobs** [comment] 2020-04-19 03:26
@yurivict Does this appear to be the same (known) issue as #4 ?

**Comment by yurivict** [comment] 2020-04-19 03:39
It appears to be the same issue.

**Comment by koobs** [comment] 2020-04-19 04:10
@yurivict Thanks!

Close duplicate of #4

**Closed by koobs** 2020-04-19 04:10 UTC
